package id3v2

type FrameID string

var SupportedFrameIDMap = map[FrameID]bool{
	"AENC": true, // [[#sec4.20|Audio encryption]]
	"APIC": true, // [#sec4.15 Attached picture]
	"COMM": true, // [#sec4.11 Comments]
	"COMR": true, // [#sec4.25 Commercial frame]
	"ENCR": true, // [#sec4.26 Encryption method registration]
	"EQUA": true, // [#sec4.13 Equalization]
	"ETCO": true, // [#sec4.6 Event timing codes]
	"GEOB": true, // [#sec4.16 General encapsulated object]
	"GRID": true, // [#sec4.27 Group identification registration]
	"IPLS": true, // [#sec4.4 Involved people list]
	"LINK": true, // [#sec4.21 Linked information]
	"MCDI": true, // [#sec4.5 Music CD identifier]
	"MLLT": true, // [#sec4.7 MPEG location lookup table]
	"OWNE": true, // [#sec4.24 Ownership frame]
	"PRIV": true, // [#sec4.28 Private frame]
	"PCNT": true, // [#sec4.17 Play counter]
	"POPM": true, // [#sec4.18 Popularimeter]
	"POSS": true, // [#sec4.22 Position synchronisation frame]
	"RBUF": true, // [#sec4.19 Recommended buffer size]
	"RVAD": true, // [#sec4.12 Relative volume adjustment]
	"RVRB": true, // [#sec4.14 Reverb]
	"SYLT": true, // [#sec4.10 Synchronized lyric/text]
	"SYTC": true, // [#sec4.8 Synchronized tempo codes]
	"TALB": true, // [#TALB Album/Movie/Show title]
	"TBPM": true, // [#TBPM BPM (beats per minute)]
	"TCOM": true, // [#TCOM Composer]
	"TCON": true, // [#TCON Content type]
	"TCOP": true, // [#TCOP Copyright message]
	"TDAT": true, // [#TDAT Date]
	"TDLY": true, // [#TDLY Playlist delay]
	"TENC": true, // [#TENC Encoded by]
	"TEXT": true, // [#TEXT Lyricist/Text writer]
	"TFLT": true, // [#TFLT File type]
	"TIME": true, // [#TIME Time]
	"TIT1": true, // [#TIT1 Content group description]
	"TIT2": true, // [#TIT2 Title/songname/content description]
	"TIT3": true, // [#TIT3 Subtitle/Description refinement]
	"TKEY": true, // [#TKEY Initial key]
	"TLAN": true, // [#TLAN Language(s)]
	"TLEN": true, // [#TLEN Length]
	"TMED": true, // [#TMED Media type]
	"TOAL": true, // [#TOAL Original album/movie/show title]
	"TOFN": true, // [#TOFN Original filename]
	"TOLY": true, // [#TOLY Original lyricist(s)/text writer(s)]
	"TOPE": true, // [#TOPE Original artist(s)/performer(s)]
	"TORY": true, // [#TORY Original release year]
	"TOWN": true, // [#TOWN File owner/licensee]
	"TPE1": true, // [#TPE1 Lead performer(s)/Soloist(s)]
	"TPE2": true, // [#TPE2 Band/orchestra/accompaniment]
	"TPE3": true, // [#TPE3 Conductor/performer refinement]
	"TPE4": true, // [#TPE4 Interpreted, remixed, or otherwise modified by]
	"TPOS": true, // [#TPOS Part of a set]
	"TPUB": true, // [#TPUB Publisher]
	"TRCK": true, // [#TRCK Track number/Position in set]
	"TRDA": true, // [#TRDA Recording dates]
	"TRSN": true, // [#TRSN Internet radio station name]
	"TRSO": true, // [#TRSO Internet radio station owner]
	"TSIZ": true, // [#TSIZ Size]
	"TSRC": true, // [#TSRC ISRC (international standard recording code)]
	"TSSE": true, // [#TSEE Software/Hardware and settings used for encoding]
	"TYER": true, // [#TYER Year]
	"TXXX": true, // [#TXXX User defined text information frame]
	"UFID": true, // [#sec4.1 Unique file identifier]
	"USER": true, // [#sec4.23 Terms of use]
	"USLT": true, // [#sec4.9 Unsychronized lyric/text transcription]
	"WCOM": true, // [#WCOM Commercial information]
	"WCOP": true, // [#WCOP Copyright/Legal information]
	"WOAF": true, // [#WOAF Official audio file webpage]
	"WOAR": true, // [#WOAR Official artist/performer webpage]
	"WOAS": true, // [#WOAS Official audio source webpage]
	"WORS": true, // [#WORS Official internet radio station homepage]
	"WPAY": true, // [#WPAY Payment]
	"WPUB": true, // [#WPUB Publishers official webpage]
	"WXXX": true, // [#WXXX User defined URL link frame]
}
